language: scala

sudo: required

dist: trusty

jdk:
- oraclejdk8

scala:
- 2.12.8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.nvm

env:
  global:
  - TRAVIS_NODE_VERSION="5"

addons:
  apt:
    packages:
    - graphviz

before_install:
- export PATH=${PATH}:./vendor/bundle

before_install:
- git fetch --tags

install:
- scripts/travis/setup.sh

stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - env: TEST="compile"
    script: scripts/travis/build.sh
  - env: TEST="formatting"
    script: sbt scalafmtCheck scalafmtSbtCheck
  - stage: release
    script: sbt ci-release

branches:
  only:
  - master